language: c++
before_install:
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libcr-dev mpich2 mpich2-doc
install: 
- ./configure --prefix=/home/travis/build/jaredgk/ima2p/
- make 
- make install 
- mpicxx -DMPI_ENABLED -o IMa2p src/*.cpp
